### ISSUE TITLE
一个使用的疑问

### ISSUE THREAD

**Issue by TPQuietBro** [zanyfly/Dr.Light#1]
看你的使用方法,我不是很明白,能说具体一点吗,是我需要对每一个想监听的类都要写一个加toggle的方法么

**Comment by zanyfly** [comment]
@TPQuietBro 不用。只有kvo的需要在相关对象开启下。 代码还有个DRLIGHT_TOGGLE_CLOSED 宏，打开这个表示在debug模式下，保护也起作用，建议保持注释掉或者直接不用

**Comment by TPQuietBro** [comment]
ok,明白了,谢谢
