### ISSUE TITLE
-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by gratefulHeart** [zanyfly/Dr.Light#2]
NSDictionary *dict = @{@"key":@{@"kk":@"vv"}};
    NSString *keyValue = dict[@"key"];
    BOOL isTrue = [keyValue isEqualToString:@"11"];
    if (isTrue) {
        NSLog(@"YES");
    }
    else{
        NSLog(@"NO");
    }

这样是不是避免不了

**Comment by zanyfly** [comment]
越界和类型检查没有处理。原因也是因为和业务交叉太多，建议可以根据自身业务自行实现。
